# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_screen(object):
    def setupUi(self, Screen):
        Screen.setObjectName("Screen")
        Screen.resize(681, 400)
        self.centralwidget = QWidget(Screen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropframe = QFrame(self.centralwidget)
        self.dropframe.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"    \n"
"    color: rgb(255, 182, 64);\n"
"    border-radius: 10px;\n"
"}")
        self.dropframe.setFrameShape(QFrame.StyledPanel)
        self.dropframe.setFrameShadow(QFrame.Raised)
        self.dropframe.setObjectName("dropframe")
        self.label = QLabel(self.dropframe)
        self.label.setGeometry(QRect(0, 70, 661, 61))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_description = QLabel(self.dropframe)
        self.label_description.setGeometry(QRect(0, 130, 661, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_description.setAlignment(Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.progressBar = QProgressBar(self.dropframe)
        self.progressBar.setGeometry(QRect(60, 270, 561, 21))
        font = QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(85, 255, 255);\n"
"    color:rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.488, x2:1, y2:0.455, stop:0 rgba(170, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_loading = QLabel(self.dropframe)
        self.label_loading.setGeometry(QRect(0, 300, 661, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_loading.setFont(font)
        self.label_loading.setStyleSheet("color: rgb(230, 230, 230);")
        self.label_loading.setAlignment(Qt.AlignCenter)
        self.label_loading.setObjectName("label_loading")
        self.label_4 = QLabel(self.dropframe)
        self.label_4.setGeometry(QRect(0, 340, 651, 31))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"color: rgb(207, 255, 219);")
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.dropframe)
        Screen.setCentralWidget(self.centralwidget)

        self.retranslateUi(Screen)
        QMetaObject.connectSlotsByName(Screen)

    def retranslateUi(self, Screen):
        _translate = QCoreApplication.translate
        Screen.setWindowTitle(_translate("Screen", "Screen"))
        self.label.setText(_translate("Screen", "<strong>VEHICLE </strong>INVENTORY"))
        self.label_description.setText(_translate("Screen", "<strong>APP </strong>DESCRIPTION"))
        self.label_loading.setText(_translate("Screen", "<html><head/><body><p>loading...</p></body></html>"))
        self.label_4.setText(_translate("Screen", "<html><head/><body><p><span style=\" font-weight:600;\">Created: </span>Jenish Patel</p></body></html>"))



